server:
  port: 8097

spring:
  application:
    name: agent-tools-demo
  ai:
    openai:
      api-key: "sk-4ZkNj89GHt26K4lyfl1JNOQuPtUeV5ktXUs8T1VbJ1iS7R5Y"
      base-url: "https://992236.xyz/v1"
      chat:
        options:
          model: "gemini-2.5-pro"
          stream: false

logging:
  level:
    root: info
    org.springframework.ai: info
